spring:

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    driver-class-name: ${DB_DRIVE}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}

jwt:
  secret_key: ${SECRET_KEY}
  access_exp: ${ACCESS_EXP}
  refresh_exp: ${REFRESH_EXP}